name: mcp-start
root: ./

windows:
  - kolada: uv run --package kolada kolada
  - skolverket: uv run --package skolverket skolverket
  - time: uv run --package time time
  - scb: uv run --package scb scb
